"""Unit tests for _run_post_sync_ops() + SQL builder helpers in proxy/prefect_flows_runner.py.

SQL is now built inside prefect-proxy from raw op config (not pre-generated by
backend). BigQuery uses live table metadata (partition/cluster spec) to build
CREATE OR REPLACE that Airbyte-partitioned tables will accept.
"""
import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from proxy.prefect_flows_runner import (
    _build_bigquery_cast_sql,
    _build_postgres_cast_sql,
    _normalize_column_name,
    _run_post_sync_ops,
)


POSTGRES_CREDS = {
    "host": "localhost",
    "port": 5432,
    "database": "mydb",
    "user": "myuser",
    "password": "secret",
}

BIGQUERY_CREDS = {
    "type": "service_account",
    "project_id": "my-project",
    "private_key_id": "key-id",
    "private_key": "key",
    "client_email": "svc@my-project.iam.gserviceaccount.com",
    "client_id": "123",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
}


def _secret_block(wtype: str, creds: dict):
    block = MagicMock()
    block.get.return_value = json.dumps({"wtype": wtype, "creds": creds})
    return block


def _bq_table_meta(partition_field=None, partition_type="DAY", cluster_fields=None):
    """Simulate a google.cloud.bigquery.Table result from client.get_table()."""
    meta = MagicMock()
    if partition_field:
        meta.time_partitioning = MagicMock(field=partition_field, type_=partition_type)
    else:
        meta.time_partitioning = None
    meta.clustering_fields = cluster_fields
    return meta


# ---------------------------------------------------------------------------
# Column normalization
# ---------------------------------------------------------------------------


def test_normalize_column_name_preserves_valid_chars():
    assert _normalize_column_name("Measure_7") == "Measure_7"
    assert _normalize_column_name("dollar$sign") == "dollar$sign"


def test_normalize_column_name_replaces_specials():
    assert _normalize_column_name("Measure 7") == "Measure_7"
    assert _normalize_column_name("column.name") == "column_name"
    assert _normalize_column_name("user@email") == "user_email"


# ---------------------------------------------------------------------------
# _build_postgres_cast_sql
# ---------------------------------------------------------------------------


def test_postgres_single_cast():
    sql = _build_postgres_cast_sql("dest", "orders", {"amount": "numeric"})
    assert (
        sql
        == 'ALTER TABLE "dest"."orders"\n  ALTER COLUMN "amount" TYPE numeric USING "amount"::numeric'
    )


def test_postgres_multiple_casts():
    sql = _build_postgres_cast_sql(
        "dest", "orders", {"amount": "numeric", "created_at": "timestamp"}
    )
    assert '"amount"' in sql
    assert '"created_at"' in sql
    assert "ALTER TABLE" in sql


def test_postgres_column_name_normalized():
    """Column names with spaces get underscored to match Airbyte's destination convention."""
    sql = _build_postgres_cast_sql("dest", "orders", {"Measure 7": "numeric"})
    assert '"Measure_7"' in sql
    assert '"Measure 7"' not in sql


def test_postgres_unknown_type_raises():
    with pytest.raises(ValueError, match="Unsupported cast type for Postgres"):
        _build_postgres_cast_sql("s", "t", {"col": "jsonb"})


# ---------------------------------------------------------------------------
# _build_bigquery_cast_sql
# ---------------------------------------------------------------------------


def test_bigquery_single_cast_no_partition():
    sql = _build_bigquery_cast_sql(
        "my-project", "dest", "orders", {"amount": "numeric"}, _bq_table_meta()
    )
    assert "CREATE OR REPLACE TABLE `my-project`.`dest`.`orders`" in sql
    assert "PARTITION BY" not in sql
    assert "CLUSTER BY" not in sql
    assert "SELECT * REPLACE" in sql
    assert "CAST(`amount` AS NUMERIC) AS `amount`" in sql


def test_bigquery_with_partition_and_cluster():
    """The Airbyte-standard spec: DAY partition on _airbyte_extracted_at, cluster on same."""
    meta = _bq_table_meta(
        partition_field="_airbyte_extracted_at",
        partition_type="DAY",
        cluster_fields=["_airbyte_extracted_at"],
    )
    sql = _build_bigquery_cast_sql("my-project", "dest", "orders", {"amount": "numeric"}, meta)
    assert "PARTITION BY DATE(`_airbyte_extracted_at`)" in sql
    assert "CLUSTER BY `_airbyte_extracted_at`" in sql
    assert "CAST(`amount` AS NUMERIC) AS `amount`" in sql


def test_bigquery_cluster_with_primary_keys():
    meta = _bq_table_meta(
        partition_field="_airbyte_extracted_at",
        partition_type="DAY",
        cluster_fields=["_airbyte_extracted_at", "id", "order_id"],
    )
    sql = _build_bigquery_cast_sql("my-project", "dest", "orders", {"amount": "numeric"}, meta)
    assert "CLUSTER BY `_airbyte_extracted_at`, `id`, `order_id`" in sql


def test_bigquery_partition_type_hour():
    meta = _bq_table_meta(partition_field="ts", partition_type="HOUR")
    sql = _build_bigquery_cast_sql("proj", "s", "t", {"col": "numeric"}, meta)
    assert "PARTITION BY TIMESTAMP_TRUNC(`ts`, HOUR)" in sql


def test_bigquery_unknown_partition_type_skipped():
    """If we don't know the partition type, we skip PARTITION BY (safer than emitting bad SQL)."""
    meta = _bq_table_meta(partition_field="ts", partition_type="WEEK")
    sql = _build_bigquery_cast_sql("proj", "s", "t", {"col": "numeric"}, meta)
    assert "PARTITION BY" not in sql


def test_bigquery_column_name_normalized():
    sql = _build_bigquery_cast_sql("proj", "s", "t", {"Measure 7": "numeric"}, _bq_table_meta())
    assert "CAST(`Measure_7` AS NUMERIC) AS `Measure_7`" in sql


def test_bigquery_unknown_type_raises():
    with pytest.raises(ValueError, match="Unsupported cast type for BigQuery"):
        _build_bigquery_cast_sql("proj", "s", "t", {"col": "STRUCT"}, _bq_table_meta())


# ---------------------------------------------------------------------------
# _run_post_sync_ops — no-op cases
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_noop_when_ops_empty():
    with patch("proxy.prefect_flows_runner.Secret") as mock_secret:
        mock_secret.aload = AsyncMock()
        await _run_post_sync_ops(env={}, ops=[])
        mock_secret.aload.assert_not_called()


@pytest.mark.asyncio
async def test_noop_when_no_secret_block_in_env():
    with patch("proxy.prefect_flows_runner.Secret") as mock_secret:
        mock_secret.aload = AsyncMock()
        await _run_post_sync_ops(
            env={},
            ops=[{"type": "cast", "schema": "s", "table": "t", "column_casts": {"c": "numeric"}}],
        )
        mock_secret.aload.assert_not_called()


@pytest.mark.asyncio
async def test_noop_when_no_cast_ops():
    """Non-cast ops are filtered out and don't trigger a warehouse connection."""
    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "psycopg2.connect"
    ) as mock_connect:
        mock_secret.aload = AsyncMock(return_value=_secret_block("postgres", POSTGRES_CREDS))
        await _run_post_sync_ops(
            env={"dbt-profile-secret-block": "my-block"},
            ops=[{"type": "unknown", "sql": "SELECT 1"}],
        )
        mock_connect.assert_not_called()


# ---------------------------------------------------------------------------
# _run_post_sync_ops — Postgres path
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_postgres_executes_generated_sql():
    mock_conn = MagicMock()
    mock_cursor = MagicMock()
    mock_conn.cursor.return_value.__enter__ = lambda s: mock_cursor
    mock_conn.cursor.return_value.__exit__ = MagicMock(return_value=False)

    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "psycopg2.connect", return_value=mock_conn
    ) as mock_connect:
        mock_secret.aload = AsyncMock(return_value=_secret_block("postgres", POSTGRES_CREDS))
        await _run_post_sync_ops(
            env={"dbt-profile-secret-block": "my-block"},
            ops=[
                {
                    "type": "cast",
                    "schema": "dest",
                    "table": "orders",
                    "column_casts": {"amount": "numeric"},
                }
            ],
        )

    mock_connect.assert_called_once_with(
        host="localhost",
        port=5432,
        dbname="mydb",
        user="myuser",
        password="secret",
    )
    # Exactly one ALTER TABLE statement was executed
    mock_cursor.execute.assert_called_once()
    executed_sql = mock_cursor.execute.call_args.args[0]
    assert 'ALTER TABLE "dest"."orders"' in executed_sql
    assert 'ALTER COLUMN "amount" TYPE numeric' in executed_sql
    mock_conn.close.assert_called_once()


@pytest.mark.asyncio
async def test_postgres_closes_connection_on_error():
    """Connection is closed even when execute raises."""
    mock_conn = MagicMock()
    mock_cursor = MagicMock()
    mock_cursor.execute.side_effect = Exception("syntax error")
    mock_conn.cursor.return_value.__enter__ = lambda s: mock_cursor
    mock_conn.cursor.return_value.__exit__ = MagicMock(return_value=False)

    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "psycopg2.connect", return_value=mock_conn
    ):
        mock_secret.aload = AsyncMock(return_value=_secret_block("postgres", POSTGRES_CREDS))
        with pytest.raises(Exception, match="syntax error"):
            await _run_post_sync_ops(
                env={"dbt-profile-secret-block": "my-block"},
                ops=[
                    {
                        "type": "cast",
                        "schema": "dest",
                        "table": "orders",
                        "column_casts": {"amount": "numeric"},
                    }
                ],
            )

    mock_conn.close.assert_called_once()


# ---------------------------------------------------------------------------
# _run_post_sync_ops — BigQuery path
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_bigquery_fetches_metadata_and_executes():
    """Verify: get_table is called, generated SQL includes partition/cluster
    from the live metadata, and client.close() runs afterwards."""
    mock_client = MagicMock()
    mock_client.get_table.return_value = _bq_table_meta(
        partition_field="_airbyte_extracted_at",
        partition_type="DAY",
        cluster_fields=["_airbyte_extracted_at"],
    )
    mock_query_job = MagicMock()
    mock_client.query.return_value = mock_query_job

    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "google.oauth2.service_account.Credentials.from_service_account_info"
    ), patch("google.cloud.bigquery.Client", return_value=mock_client):
        mock_secret.aload = AsyncMock(return_value=_secret_block("bigquery", BIGQUERY_CREDS))
        await _run_post_sync_ops(
            env={"dbt-profile-secret-block": "my-block"},
            ops=[
                {
                    "type": "cast",
                    "schema": "dest",
                    "table": "orders",
                    "column_casts": {"amount": "numeric"},
                }
            ],
        )

    mock_client.get_table.assert_called_once_with("my-project.dest.orders")
    mock_client.query.assert_called_once()
    executed_sql = mock_client.query.call_args.args[0]
    assert "CREATE OR REPLACE TABLE `my-project`.`dest`.`orders`" in executed_sql
    assert "PARTITION BY DATE(`_airbyte_extracted_at`)" in executed_sql
    assert "CLUSTER BY `_airbyte_extracted_at`" in executed_sql
    assert "CAST(`amount` AS NUMERIC) AS `amount`" in executed_sql
    mock_query_job.result.assert_called_once()
    mock_client.close.assert_called_once()


@pytest.mark.asyncio
async def test_bigquery_closes_client_on_error():
    """Client is closed even when query raises."""
    mock_client = MagicMock()
    mock_client.get_table.return_value = _bq_table_meta()
    mock_client.query.side_effect = Exception("quota exceeded")

    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "google.oauth2.service_account.Credentials.from_service_account_info"
    ), patch("google.cloud.bigquery.Client", return_value=mock_client):
        mock_secret.aload = AsyncMock(return_value=_secret_block("bigquery", BIGQUERY_CREDS))
        with pytest.raises(Exception, match="quota exceeded"):
            await _run_post_sync_ops(
                env={"dbt-profile-secret-block": "my-block"},
                ops=[
                    {
                        "type": "cast",
                        "schema": "dest",
                        "table": "orders",
                        "column_casts": {"amount": "numeric"},
                    }
                ],
            )

    mock_client.close.assert_called_once()


@pytest.mark.asyncio
async def test_bigquery_closes_client_when_get_table_fails():
    """Client is closed even if get_table (metadata fetch) raises."""
    mock_client = MagicMock()
    mock_client.get_table.side_effect = Exception("table not found")

    with patch("proxy.prefect_flows_runner.Secret") as mock_secret, patch(
        "google.oauth2.service_account.Credentials.from_service_account_info"
    ), patch("google.cloud.bigquery.Client", return_value=mock_client):
        mock_secret.aload = AsyncMock(return_value=_secret_block("bigquery", BIGQUERY_CREDS))
        with pytest.raises(Exception, match="table not found"):
            await _run_post_sync_ops(
                env={"dbt-profile-secret-block": "my-block"},
                ops=[
                    {
                        "type": "cast",
                        "schema": "dest",
                        "table": "orders",
                        "column_casts": {"amount": "numeric"},
                    }
                ],
            )

    mock_client.close.assert_called_once()
