version: "3.9"
services:
  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2-python3.10
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=${PREFECT_API_URL}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=${DATABASE_CONNECTION_URL}
      # Uncomment the following line to use the 'S3 Bucket' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2-python3.10
    restart: always
    entrypoint:
      [
        "/opt/prefect/entrypoint.sh",
        "prefect",
        "agent",
        "start",
        "-q",
        ${PREFECT_WORK_QUEUE_NAME},
        "--pool",
        ${PREFECT_POOL_NAME}
      ]
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}

  ## Prefect Proxy
  prefect_proxy:
    build: .
    image: prefect_proxy
    restart: always

volumes:
  prefect:
networks:
  default:
    name: prefect-network
