name: Proxy CI 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create logs directory
        run: |
          mkdir -p logs

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Add remote host key to known_hosts
        run: ssh-keyscan ${{ secrets.SERVERIP }} >> ~/.ssh/known_hosts

      - name: Create Google App credentials file
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > /tmp/google_credentials.json

      - name: Test with pytest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google_credentials.json
          LOGDIR: ${{ github.workspace }}/logs
        run: |
          mkdir -p $LOGDIR
          uv run coverage run --omit=proxy/flows.py,proxy/prefect_flows.py -m pytest --durations=20 --asyncio-mode=auto
          uv run coverage xml

      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Check coverage percentage
        run: |
          uv run coverage report --fail-under=70
